name: "Helm Deploy"
description: "Deploy application using Helm with OCI chart support"

inputs:
  release-name:
    description: "Helm release name"
    required: true
  namespace:
    description: "Target Kubernetes namespace"
    required: true
  chart:
    description: "OCI chart reference (e.g., oci://ghcr.io/org/charts/app)"
    required: true
  chart-version:
    description: "Chart version to deploy"
    required: true
  values-files:
    description: "Newline-separated list of values files to apply"
    required: false
    default: ""
  set-values:
    description: "Newline-separated key=value pairs for --set flags"
    required: false
    default: ""
  registry:
    description: "OCI registry hostname for chart pull"
    required: false
    default: "ghcr.io"
  registry-username:
    description: "Registry username"
    required: true
  registry-password:
    description: "Registry password or token"
    required: true
  timeout:
    description: "Deployment timeout"
    required: false
    default: "5m"
  create-namespace:
    description: "Create namespace if it doesn't exist"
    required: false
    default: "true"
  wait:
    description: "Wait for deployment to complete"
    required: false
    default: "true"
  atomic:
    description: "Rollback on deployment failure"
    required: false
    default: "true"

outputs:
  revision:
    description: "Helm release revision number"
    value: ${{ steps.deploy.outputs.revision }}

runs:
  using: "composite"
  steps:
    - name: Login to OCI registry
      shell: bash
      run: |
        echo "${{ inputs.registry-password }}" | \
          helm registry login ${{ inputs.registry }} \
            -u ${{ inputs.registry-username }} \
            --password-stdin

    - name: Deploy with Helm
      id: deploy
      shell: bash
      run: |
        # Build values files arguments
        VALUES_ARGS=""
        if [ -n "${{ inputs.values-files }}" ]; then
          while IFS= read -r file; do
            [ -n "$file" ] && VALUES_ARGS="$VALUES_ARGS -f $file"
          done <<< "${{ inputs.values-files }}"
        fi

        # Build --set arguments
        SET_ARGS=""
        if [ -n "${{ inputs.set-values }}" ]; then
          while IFS= read -r pair; do
            [ -n "$pair" ] && SET_ARGS="$SET_ARGS --set $pair"
          done <<< "${{ inputs.set-values }}"
        fi

        # Build optional flags
        FLAGS=""
        [ "${{ inputs.create-namespace }}" = "true" ] && FLAGS="$FLAGS --create-namespace"
        [ "${{ inputs.wait }}" = "true" ] && FLAGS="$FLAGS --wait"
        [ "${{ inputs.atomic }}" = "true" ] && FLAGS="$FLAGS --atomic"

        # Deploy
        helm upgrade --install ${{ inputs.release-name }} \
          ${{ inputs.chart }} \
          --version ${{ inputs.chart-version }} \
          --namespace ${{ inputs.namespace }} \
          --timeout ${{ inputs.timeout }} \
          $VALUES_ARGS \
          $SET_ARGS \
          $FLAGS

        # Capture revision
        REVISION=$(helm history ${{ inputs.release-name }} \
          -n ${{ inputs.namespace }} \
          --max 1 \
          -o json | jq -r '.[0].revision')
        echo "revision=$REVISION" >> $GITHUB_OUTPUT
