name: "K8s Deploy"
description: "Deploys application to Kubernetes using Kustomize. Supports both production and preview environments."

inputs:
  app-name:
    description: "Application name (used for resource names, namespace scoping, and preview URLs)"
    required: true
  kustomize-path:
    description: "Path to kustomize overlay directory"
    required: true
  image-name:
    description: "Full image name (e.g., ghcr.io/owner/repo)"
    required: true
  image-tag:
    description: "Image tag to deploy"
    required: true
  timeout:
    description: "Rollout timeout"
    required: false
    default: "120s"
  # Preview-specific inputs
  preview:
    description: "Enable preview environment mode"
    required: false
    default: "false"
  pr-number:
    description: "Pull request number (required if preview=true)"
    required: false
    default: ""
  domain:
    description: "Base domain for preview URL (required if preview=true)"
    required: false
    default: ""

outputs:
  preview-url:
    description: "The preview environment URL (only set if preview=true)"
    value: ${{ steps.preview-config.outputs.preview_url }}
  namespace:
    description: "The Kubernetes namespace deployed to"
    value: ${{ steps.namespace.outputs.namespace }}

runs:
  using: "composite"
  steps:
    - name: Validate inputs
      shell: bash
      run: |
        set -euo pipefail

        if [[ "${{ inputs.preview }}" == "true" ]]; then
          if [[ -z "${{ inputs.pr-number }}" ]]; then
            echo "::error::pr-number is required when preview=true"
            exit 1
          fi
          if [[ -z "${{ inputs.domain }}" ]]; then
            echo "::error::domain is required when preview=true"
            exit 1
          fi
        fi

    - name: Determine namespace
      id: namespace
      shell: bash
      run: |
        set -euo pipefail

        if [[ "${{ inputs.preview }}" == "true" ]]; then
          NAMESPACE="${{ inputs.app-name }}-pr-${{ inputs.pr-number }}"
        else
          NAMESPACE=$(grep '^namespace:' "${{ inputs.kustomize-path }}/kustomization.yaml" | awk '{print $2}')
          if [[ -z "${NAMESPACE}" ]]; then
            echo "::error::Could not determine namespace from kustomization.yaml"
            exit 1
          fi
        fi

        echo "namespace=${NAMESPACE}" >> $GITHUB_OUTPUT
        echo "Deploying to namespace: ${NAMESPACE}"

    - name: Configure preview environment
      id: preview-config
      if: inputs.preview == 'true'
      shell: bash
      working-directory: ${{ inputs.kustomize-path }}
      env:
        APP_NAME: ${{ inputs.app-name }}
        PR_NUMBER: ${{ inputs.pr-number }}
        DOMAIN: ${{ inputs.domain }}
        NAMESPACE: ${{ steps.namespace.outputs.namespace }}
      run: |
        set -euo pipefail

        PREVIEW_URL="${APP_NAME}-pr-${PR_NUMBER}-preview.${DOMAIN}"
        echo "preview_url=https://${PREVIEW_URL}" >> $GITHUB_OUTPUT
        echo "Preview URL: https://${PREVIEW_URL}"

        # Set namespace dynamically (affects all resources)
        kustomize edit set namespace ${NAMESPACE}

        # Generate namespace resource with dynamic name and labels
        cat > namespace.yaml <<EOF
        apiVersion: v1
        kind: Namespace
        metadata:
          name: ${NAMESPACE}
          labels:
            environment: preview
            pr-number: "${PR_NUMBER}"
        EOF

        # Patch only the ingress hostname using JSON patch (preserves all other config)
        cat > ingress-patch.yaml <<EOF
        - op: replace
          path: /spec/rules/0/host
          value: ${PREVIEW_URL}
        EOF

        # Add JSON patch targeting the ingress (if not already present)
        if ! grep -q "ingress-patch.yaml" kustomization.yaml; then
          kustomize edit add patch --path ingress-patch.yaml --kind Ingress --name ${APP_NAME}
        fi

    - name: Set image tag
      shell: bash
      working-directory: ${{ inputs.kustomize-path }}
      run: |
        set -euo pipefail
        kustomize edit set image ${{ inputs.image-name }}=${{ inputs.image-name }}:${{ inputs.image-tag }}

    - name: Apply manifests
      shell: bash
      working-directory: ${{ inputs.kustomize-path }}
      run: |
        set -euo pipefail
        kubectl apply -k .

    - name: Cleanup preview patch files
      if: inputs.preview == 'true'
      shell: bash
      working-directory: ${{ inputs.kustomize-path }}
      run: |
        rm -f ingress-patch.yaml

    - name: Wait for rollout
      shell: bash
      run: |
        set -euo pipefail
        kubectl rollout status deployment/${{ inputs.app-name }} \
          -n ${{ steps.namespace.outputs.namespace }} \
          --timeout=${{ inputs.timeout }}
