name: "K8s Setup"
description: "Sets up Tailscale, kubectl, and kubeconfig for K8s cluster access"

inputs:
  tailscale-oauth-client-id:
    description: "Tailscale OAuth client ID"
    required: true
  tailscale-oauth-secret:
    description: "Tailscale OAuth client secret"
    required: true
  k3s-ca-cert:
    description: "K3s cluster CA certificate (base64)"
    required: true
  k3s-token:
    description: "K3s service account token"
    required: true
  k3s-host:
    description: "K3s node Tailscale hostname"
    required: false
    default: "k3s-node"
  kubectl-version:
    description: "kubectl version to install"
    required: false
    default: "v1.28.0"

runs:
  using: "composite"
  steps:
    - name: Setup Tailscale
      uses: tailscale/github-action@v2
      with:
        oauth-client-id: ${{ inputs.tailscale-oauth-client-id }}
        oauth-secret: ${{ inputs.tailscale-oauth-secret }}
        tags: tag:ci

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: ${{ inputs.kubectl-version }}

    - name: Generate kubeconfig
      shell: bash
      run: |
        K3S_IP=$(tailscale ip -4 ${{ inputs.k3s-host }})
        mkdir -p ~/.kube
        cat > ~/.kube/config << EOF
        apiVersion: v1
        kind: Config
        clusters:
          - name: k3s
            cluster:
              server: https://${K3S_IP}:6443
              certificate-authority-data: ${{ inputs.k3s-ca-cert }}
        contexts:
          - name: k3s
            context:
              cluster: k3s
              user: github-ci
        current-context: k3s
        users:
          - name: github-ci
            user:
              token: ${{ inputs.k3s-token }}
        EOF
        chmod 600 ~/.kube/config
