name: "K8s Preview Comment"
description: "Comments on a PR with preview environment details"

inputs:
  preview-url:
    description: "The preview environment URL"
    required: true
  namespace:
    description: "The Kubernetes namespace"
    required: true
  image:
    description: "The Docker image deployed"
    required: true
  status:
    description: "Deployment status: deploying or deployed"
    required: false
    default: "deployed"
  cpu-limit:
    description: "CPU limit for the container"
    required: false
    default: ""
  memory-limit:
    description: "Memory limit for the container"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Comment on PR
      uses: actions/github-script@v7
      env:
        PREVIEW_URL: ${{ inputs.preview-url }}
        NAMESPACE: ${{ inputs.namespace }}
        IMAGE: ${{ inputs.image }}
        STATUS: ${{ inputs.status }}
        CPU_LIMIT: ${{ inputs.cpu-limit }}
        MEMORY_LIMIT: ${{ inputs.memory-limit }}
      with:
        script: |
          const script = require('./.github/actions/k8s-preview-comment/comment.cjs')
          await script({ github, context, core })
